## Linear Algebra Fundamentals
- **Practice** : Implement matrix operations, solve linear equations with NumPy 
- **Assignment** : Build PCA from scratch using only NumPy

The primary matrix operations are: 
Addition: Adding corresponding elements of two matrices of the same size.
Subtraction: Subtracting corresponding elements of two matrices of the same size.
Scalar Multiplication: Multiplying each element of a matrix by a constant.
Matrix Multiplication: Multiplying two matrices (requires the number of columns in the first matrix to equal the number of rows in the second matrix).
Transpose: Swapping the rows and columns of a matrix.
Inverse: Finding a matrix that, when multiplied by the original matrix, results in the identity matrix (only applicable to square, non-singular matrices). 

In [3]:
import numpy as np

In [15]:
def add_2d_matrices(a, b):
    # creating a matix with the same dimensions as a
    c = np.empty_like(a) # found this in the numpy docs for array creation: 
    # https://numpy.org/doc/2.2/reference/routines.array-creation.html#routines-array-creation
    # iterate through each value in a and b, adding them and storing 
    # in the matrix c
    for i in range(0,a.shape[0]):
        for j in range(0,a.shape[1]): 
            c[i][j] = a[i][j] + b[i][j]
        
    return c

In [16]:
# mostly the same as adding, just subracting instead
def sub_2d_matrices(a, b):
    c = np.empty_like(a)
    for i in range(0,a.shape[0]):
        for j in range(0,a.shape[1]): 
            c[i][j] = a[i][j] - b[i][j]        
    return c

In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
y = np.array([[7, 8, 9], [10, 11, 12]], np.int32)


In [12]:
add_2d_matrices(x,y)

array([[ 8, 10, 12],
       [14, 16, 18]], dtype=int32)

In [13]:
x + y == add_2d_matrices(x,y)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [19]:
sub_2d_matrices(x,y)

array([[-6, -6, -6],
       [-6, -6, -6]], dtype=int32)

In [20]:
x - y == sub_2d_matrices(x,y)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [24]:
# Iterate through all the values of matrix b and multiply by scalar a
def scalar_mult(a, b):
    c = np.empty_like(b)
    for i in range(0,b.shape[0]):
        for j in range(0,b.shape[1]): 
            c[i][j] = a * b[i][j]        
    return c

In [25]:
scalar_mult(2, x)

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [26]:
2 * x == scalar_mult(2, x)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [47]:
x[:,0]

array([1, 4], dtype=int32)

In [12]:
z[0]

NameError: name 'z' is not defined

In [51]:
z[0] * x[:,0] # vector multiplication of the first row of z and first col of x

array([1, 8])

In [52]:
sum(z[0] * x[:,0])

np.int64(9)

In [55]:
def mat_mul(a, b):
    # Checking the matrix dimensions
    if a.shape[1] != b.shape[0]:
        return None
    c = np.empty((a.shape[0], b.shape[1])) # empty matrix with first dimension of a and second of b
    # iterate through each row of a and column of b
    print(c.shape)
    for i in range(0,a.shape[0]):#row
        for j in range(0,b.shape[1]):#col 
            c[i][j] = sum(a[i] * b[:,j]) # using vector multiplication, then cheated a little and used sum to add up the vector
            print(f"c[{i}][{j}] : {c[i][j]}")
    return c

In [13]:
z = np.array([[1, 2],[3, 4], [5, 6]])
mat_mul(z,x)

NameError: name 'mat_mul' is not defined

In [58]:
def transpose(a):
    c = np.empty((a.shape[1], a.shape[0]))
    for i in range(0,a.shape[0]):
        for j in range(0,a.shape[1]):
            c[j][i] = a[i][j]
    return c

In [59]:
transpose(z)

array([[1., 3., 5.],
       [2., 4., 6.]])

In [60]:
np.transpose(z) == transpose(z)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [18]:
def dot_product(a, b):
    pairs = zip(a,b)
    products = [x * y for (x,y) in pairs]
    return sum(products)

In [5]:
a = [1,2,3]
b = [4,5,6]
dot_product(a,b)

[4, 10, 18]


32

In [7]:
dot_product(a,b) == np.dot(a,b)

[4, 10, 18]


np.True_

In [10]:
x[0]

array([1, 2, 3], dtype=int32)

In [19]:
dot_product(x[0],z[:,0])

np.int64(22)

In [20]:
# using dot product for matmul
def mat_mul(a, b):
    # Checking the matrix dimensions
    if a.shape[1] != b.shape[0]:
        return None
    c = np.empty((a.shape[0], b.shape[1])) # empty matrix with first dimension of a and second of b
    # iterate through each row of a and column of b
    print(c.shape)
    for i in range(0,a.shape[0]):#row
        for j in range(0,b.shape[1]):#col 
            # using dot product
            c[i][j] = dot_product(a[i],b[:,j])
    return c

In [31]:
mat_mul(z,x) == np.matmul(z,x)
mat_mul(z,x)

(3, 3)
(3, 3)


array([[ 9., 12., 15.],
       [19., 26., 33.],
       [29., 40., 51.]])

In [34]:
# trying matmul with enumerate, doesn't really help the code much
def mat_mul(a, b):
    # Checking the matrix dimensions
    if a.shape[1] != b.shape[0]:
        return None
    c = np.empty((a.shape[0], b.shape[1])) # empty matrix with first dimension of a and second of b
    # iterate through each row of a and column of b
    print(c.shape)
    for (i, v) in enumerate(z):
        for (j,w) in enumerate(x.T):
            c[i,j] == dot_product(v,w)
    return c

In [35]:
mat_mul(z,x)

(3, 3)


array([[ 9., 12., 15.],
       [19., 26., 33.],
       [29., 40., 51.]])

In [45]:
[[sum(a*b for a,b in zip(row, col)) for col in x.T] for row in z]

[[np.int64(9), np.int64(12), np.int64(15)],
 [np.int64(19), np.int64(26), np.int64(33)],
 [np.int64(29), np.int64(40), np.int64(51)]]

In [53]:
# matmul using list comprehension
def mat_mul(a, b):
    # Checking the matrix dimensions
    if a.shape[1] != b.shape[0]:
        return Nonek
    else:
        return [[sum(a*b for a,b in zip(row, col)) for col in x.T] for row in z]

In [54]:
mat_mul(z,x)

[[np.int64(9), np.int64(12), np.int64(15)],
 [np.int64(19), np.int64(26), np.int64(33)],
 [np.int64(29), np.int64(40), np.int64(51)]]